### PR TITLE
wikiupdater: Added Errordescription for .env not found

### PR DESCRIPTION
**Pull request by FFHener**
@noxilixon War das der Fehler den wir catchen wollten so als letztes ToDo? Sonst cancel gerne den PR. Kümmere mich ums linting wenn der Code passt, sonst lohnt sich der Aufwand nicht. Das sollte das letzte ToDo von https://github.com/stadtfunk/general/issues/136 lösen

### CODE REVIEW

**Review by noxilixon — APPROVED** [review]
Changed bahviour to use condition, because the load_dotenv function does not throw an excpetion as far as I can understand/test.

**Comment by noxilixon** [comment]
**Broken monitoring links :/ **

The name of the location (with big first letter) is used to create the collectd links. This results is a broken link with no match to the node. (See for example: https://wiki.freifunk.net/Berlin:Standorte:Fesev) If you fix it by hand (making the first letter smal) the node is matched correctly and data is shown.

The grafana links dont work at all.

**Comment by FFHener** [comment]
Grafana dont worke bc it got moved to a subsite of monitor. Template needs to be updated.

The lowercase-problem might be solveable by this https://www.mediawiki.org/wiki/Help:Extension:ParserFunctions using lc in fromt of the variable

**Comment by FFHener** [comment]
Grafana has now the same problem with the case sensitive stuff. The ``{{lc {{{foo}}} }}``thing didnt worked when i tried it quickly

**Comment by FFHener** [comment]
Fixed

**Comment by FFHener** [comment]
Merged manually w/o PR. Closing it

**Pull request closed without merging**
